name: ml_env
channels:
  - defaults
dependencies:
  - python=3.12.11
  - pandas=2.3.2
  - scikit-learn=1.7.1
  - joblib=1.5.2
  - jupyter=1.1.1
  - notebook=7.4.5
  - ipykernel=6.30.1
  - numpy=1.26.4
  - pip=25.2
  - pip:
    - graphviz